version: '3'
services:
  nginx:
    container_name: houseq-nginx
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
    tty: true
    depends_on:
      - api

  api:
    container_name: houseq-api
    build:
      context: .docker/api
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
      APP_NAME: 'Laravel'
      APP_ENV: 'development'
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost'
      LOG_CHANNEL: 'stderr'
      DB_CONNECTION: 'pgsql'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_DATABASE: 'houseq'
      DB_DATABASE_TEST: 'houseq'
      DB_USERNAME: 'houseq'
      DB_PASSWORD: 'houseq_pass'
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - 9000
    tty: true
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: houseq-db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'houseq'
      POSTGRES_PASSWORD: 'houseq_pass'
      POSTGRES_DB: 'houseq'
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data
      - ./.docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

networks:
  default:
    name: houseq